In [1]:
import torch

class Net(torch.nn.Module):
    def forward(self, x):
        z1 = 2*x[1] + x[2]
        z2 = x[1] * 3*x[3]
        z3 = -x[3]

        u1 = torch.sin(z1)
        u2 = 2*x[3] + z2
        u3 = 2*z1 + z3

        v1 = u1 - u3
        v2 = torch.sin(-u2)
        v3 = u1 * u3

        # y = torch.tensor([0.0, 0.0])
        # y[0] = torch.pow(v1, 2) + torch.pow(v3, 3)
        # y[1] = v2 * v3
        y=v2 * v3
        return y



class Net2(torch.nn.Module):
    def forward(self, x):
        z1 = 2*x[1] + x[2]
        z2 = x[1] * 3*x[3]
        z3 = -x[3]

        u1 = torch.sin(z1)
        u2 = 2*x[3] + z2
        u3 = 2*z1 + z3

        v1 = u1 - u3
        v2 = torch.sin(-u2)
        v3 = u1 * u3

        # y = torch.tensor([0.0, 0.0])
        # y[0] = torch.pow(v1, 2) + torch.pow(v3, 3)
        # y[1] = v2 * v3
        y= torch.pow(v1, 2) + torch.pow(v2, 3)
        return y



In [2]:
x = torch.tensor([0, 2, 1, 3], dtype=float,requires_grad=True)
model = Net()
y = model(x)
y.backward()
print(x.grad)
print( x.grad.equal(torch.tensor([0.0, 25.7484, 0.0614, 23.6467], dtype=torch.float64)))

# 获取需要更新的参数
params_to_update = []
for name, param in model.named_parameters():
    if param.requires_grad == True:
        params_to_update.append(param)
        print(name)
        
print(params_to_update)

x2 = torch.tensor([0, 2, 1,3], dtype=float,requires_grad=True)
model = Net2()
y = model(x2)
y.backward()
print(x2.grad)
# 判断x2.grad 是否正确，是否等于torch.tensor([0.0, 45.2487, 27.3204, -24.2664])

tensor([ 0.0000, 25.7484,  0.0614, 23.6467], dtype=torch.float64)
False
[]
tensor([  0.0000,  45.2487,  27.3204, -24.2664], dtype=torch.float64)


In [3]:
# numpy
import numpy as np

class Net3():
    def forward(self, x):
        z1 = 2*x[1] + x[2]
        z2 = x[1] * 3*x[3]
        z3 = -x[3]

        u1 = np.sin(z1)
        u2 = 2*x[3] + z2
        u3 = 2*z1 + z3

        v1 = u1 - u3
        v2 = np.sin(-u2)
        v3 = u1 * u3

        # y = np.tensor([0.0, 0.0])
        # y[0] = np.pow(v1, 2) + torch.pow(v3, 3)
        # y[1] = v2 * v3
        y=v2 * v3
        return y

    def backward(self, x):
        z1 = 2*x[1] + x[2]
        z2 = x[1] * 3*x[3]
        z3 = -x[3]

        u1 = np.sin(z1)
        u2 = 2*x[3] + z2
        u3 = 2*z1 + z3

        v1 = u1 - u3
        v2 = np.sin(-u2)
        v3 = u1 * u3

        # y = np.tensor([0.0, 0.0])
        # y[0] = np.pow(v1, 2) + torch.pow(v3, 3)
        # y[1] = v2 * v3
        # y=v2 * v3

        y1 = np.zeros(4) 
        y1[0] = 2 * np.cos(z1) * 2 * v1 + (-8*v1) + 3*x[3] *(-np.cos(u2)) * 3 * np.power(v2, 2)
        y1[1] = np.cos(z1) * 2 * v1 + (- 4 * v1)
        y1[2] = -3*x[1]*np.cos(-u2) * 3 * np.power(v2, 2) - 2 * np.cos(-u2) * 3 * np.power(v2, 2) + 2 * v1

        y2 = np.zeros(4)
        y2[0] = 2 * np.cos(z1) * u3 * v2 + 4 * u1 * v2 + 3 * x[3] * v3 * (-np.cos(-u2))
        y2[1] = np.cos(z1) * u3 * v2 + 2 * u1 * v2
        y2[2] = -3 * x[1] * np.cos(-u2) * v3 - 2 * np.cos(-u2) * v3 - u1 * v2
        
        # 输出所有变量

        return y1, y2



In [9]:
# 1
ls = [0,1,1,1]

## 对比torch自动求导和手动求导结果
x2 = torch.tensor(ls, dtype=float,requires_grad=True)
model = Net2()
y = model(x2)
y.backward()
print(x2.grad)

x = torch.tensor(ls, dtype=float,requires_grad=True)
model = Net()
y = model(x)
y.backward()
print(x.grad)

x3 = np.array(ls, dtype=float)
model = Net3()
y1, y2 = model.backward(x3)
print(y1)
print(y2)

# 2
ls = [0,2,1,3]

x2 = torch.tensor(ls, dtype=float,requires_grad=True)
model = Net2()
y = model(x2)
y.backward()
print(x2.grad)

x = torch.tensor(ls, dtype=float,requires_grad=True)
model = Net()
y = model(x)
y.backward()
print(x.grad)

## 对比torch自动求导和手动求导结果
x3 = np.array(ls, dtype=float)
model = Net3()
y1, y2 = model.backward(x3)
print(y1)
print(y2)

# 3
ls = [0,-1,-1,-3]

x2 = torch.tensor(ls, dtype=float,requires_grad=True)
model = Net2()
y = model(x2)
y.backward()
print(x2.grad)

x = torch.tensor(ls, dtype=float,requires_grad=True)
model = Net()
y = model(x)
y.backward()
print(x.grad)

x3 = np.array(ls, dtype=float)
model = Net3()
y1, y2 = model.backward(x3)
print(y1)
print(y2)


tensor([  0.0000,  55.7645,  29.0560, -13.6303], dtype=torch.float64)
tensor([ 0.0000, -9.5524, -4.4760, -1.1361], dtype=torch.float64)
[ 55.76452115  29.05602944 -13.63032285   0.        ]
[-9.55244091 -4.47599238 -1.13608365  0.        ]
tensor([  0.0000,  45.2487,  27.3204, -24.2664], dtype=torch.float64)
tensor([ 0.0000, 25.7484,  0.0614, 23.6467], dtype=torch.float64)
[ 45.24866101  27.32040539 -24.26642612   0.        ]
[25.74837188  0.06138621 23.6466917   0.        ]
tensor([  0.0000, -34.7244, -17.0961,   5.6586], dtype=torch.float64)
tensor([ 0.0000, -4.5307, -0.3793, -0.4390], dtype=torch.float64)
[-34.72443898 -17.09605945   5.65861331   0.        ]
[-4.53069629 -0.37929353 -0.4390381   0.        ]
